# Generated by Django 3.0.8 on 2020-10-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
