# Generated by Django 3.0.8 on 2020-10-05 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tourist_places',
            fields=[
                ('place_id', models.IntegerField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=30)),
                ('max_limit', models.CharField(default='50', max_length=20)),
                ('curr_booking', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist.tourist_places')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
