# Generated by Django 3.0.8 on 2020-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_auto_20201005_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_place',
            name='violation_found',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourist_place',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tourist_place',
            name='place_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
