# Generated by Django 3.0.8 on 2020-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0005_auto_20201006_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_place',
            name='global_cases',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tourist_place',
            name='place_detail',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tourist_place',
            name='today_cases',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tourist_place',
            name='today_deaths',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tourist_place',
            name='today_recovered',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
