# Generated by Django 3.0.8 on 2020-10-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0006_auto_20201006_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist_place',
            old_name='today_deaths',
            new_name='deaths',
        ),
        migrations.RenameField(
            model_name='tourist_place',
            old_name='today_recovered',
            new_name='recovered',
        ),
    ]
