# Generated by Django 3.0.8 on 2020-10-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0007_auto_20201007_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist_place',
            name='place_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
