# Generated by Django 3.0.8 on 2020-10-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0009_auto_20201007_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist_place',
            old_name='place_id',
            new_name='id',
        ),
    ]
